### ISSUE TITLE
Desktop mode refuses to display properly or to run a launcher 

### ISSUE THREAD

**Issue by UnsavedTrash** [nikp123/scrcpy-desktop#16] opened 2023-06-27 19:46 UTC
Desktop OS: Arch Linux
Desktop details: RTX 3090, R7-5700x, NVIDIA driver 535.54.03
Mobile OS: GrapheneOS
Model: Pixel 7 Pro
SCRCPY Version: 2.1

Although the script does set all the right developer options and reboots the phone after the first run, it fails to actually engage a desktop environment. I have tried many configurations and a few different versions of Null keyboard<sup>1</sup> as well as many different settings configurations of Taskbar. The secondary screen overlay does show and it gives me a slice of the view but never actually loads Taskbar. 

I also get the error 
`Host system has incompatible settings. Sorry about that.`
```
$ ./startscreen.sh 
Host system has incompatible settings. Sorry about that.
payload/stage1.sh: 1 file pushed, 0 skipped. 24.9 MB/s (881 bytes in 0.000s)
payload/stage2.sh: 1 file pushed, 0 skipped. 32.4 MB/s (1247 bytes in 0.000s)
scrcpy 2.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 700.6 MB/s (56955 bytes in 0.000s)
-----------------------------------------------------
|                                                   |
|  Please unlock the phone once the screen appears  |
|                                                   |
-----------------------------------------------------
SCRCPY PID: 82832
[server] INFO: Device: [Google] google Pixel 7 Pro (Android 13)
[server] WARN: Display doesn't have FLAG_SUPPORTS_PROTECTED_BUFFERS flag, mirroring can be restricted
INFO: USB device: 2B051FDH300DEP (18d1:4ee7) Google Pixel 7 Pro
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 535.54.03
INFO: Trilinear filtering enabled
INFO: Texture: 1080x2336
[server] INFO: Device screen turned off
```

The SCRCPY window opens in the standard resolution of the pixel as if I was running SCRCPY unmodified. The only difference being no ability to interact, see any apps, and the bottom third of the screen displays nothing.

![image](https://github.com/nikp123/scrcpy-desktop/assets/75506304/e1205520-9b8f-4cba-a9ee-dca915613c47)

If I attempt to expand the window it also shows no additional image to the left or right, although in the hovering overlay for the emulated second display when looking at the phone shows much more of the image. Despite the hovering 2nd display showing more of the image it still shows no Taskbar, just the wallpaper.

![image](https://github.com/nikp123/scrcpy-desktop/assets/75506304/67f15df3-a20d-4d50-bc71-fc435a277ec2)

Phone POV
![image](https://github.com/nikp123/scrcpy-desktop/assets/75506304/b4ac84f2-12af-4796-be88-f045ea12f3cb)

<sup>1</sup> null keyboard is no longer available on google play so the read me may need updating.

**Comment by nikp123** [comment] 2023-06-28 10:21
Also please try launching this script with the resolution and density already set:
```./startscreen.sh 1920x1080 120```

**Comment by UnsavedTrash** [comment] 2023-06-29 00:20
running it like that yields identical behavior to what was initially reported.

```
$ ./startscreen.sh 1920x1080 120
* daemon not running; starting now at tcp:5037
* daemon started successfully
payload/stage1.sh: 1 file pushed, 0 skipped. 5.7 MB/s (881 bytes in 0.000s)
payload/stage2.sh: 1 file pushed, 0 skipped. 7.0 MB/s (1247 bytes in 0.000s)
scrcpy 2.1 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 142.1 MB/s (56955 bytes in 0.000s)
-----------------------------------------------------
|                                                   |
|  Please unlock the phone once the screen appears  |
|                                                   |
-----------------------------------------------------
SCRCPY PID: 5693
[server] INFO: Device: [Google] google Pixel 7 Pro (Android 13)
[server] WARN: Display doesn't have FLAG_SUPPORTS_PROTECTED_BUFFERS flag, mirroring can be restricted
INFO: USB device: 2B051FDH300DEP (18d1:4ee7) Google Pixel 7 Pro
INFO: Renderer: opengl
INFO: OpenGL version: 4.6.0 NVIDIA 535.54.03
INFO: Trilinear filtering enabled
INFO: Texture: 1080x2336
[server] INFO: Device screen turned off


```

**Comment by kinostl** [comment] 2023-07-13 07:01
```bash
    ~/scrcpy-desktop    main    ./startscreen.sh     ✔ 
scrcpy 2.1 <https://github.com/Genymobile/scrcpy>
payload/stage1.sh: 1 file push...5.8 MB/s (881 bytes in 0.000s)
payload/stage2.sh: 1 file push....3 MB/s (1247 bytes in 0.000s)
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 212.0 MB/s (56955 bytes in 0.000s)
-----------------------------------------------------
|                                                   |
|  Please unlock the phone once the screen appears  |
|                                                   |
-----------------------------------------------------
SCRCPY PID: 43660
[server] INFO: Device: [Google] google Pixel 6a (Android 13)
INFO: USB device: 26101JEGR01982 (18d1:4ee7) Google Pixel 6a
[server] WARN: Display doesn't have FLAG_SUPPORTS_PROTECTED_BUFFERS flag, mirroring can be restricted
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 23.0.4
INFO: Trilinear filtering enabled
INFO: Texture: 1080x2400
[server] INFO: Device screen turned off
```

I am also experiencing this issue. It was working the day before yesterday, before I did my weekly computer updates, if that provides any hints.

**Comment by nikp123** [comment] 2023-07-13 10:40
can you give me your ``/var/log/pacman.log`` i may find what *might* be the offending package @kinostl

**Comment by kinostl** [comment] 2023-07-13 12:59
@nikp123 Sure thing. 

[pacman.log](https://github.com/nikp123/scrcpy-desktop/files/12039595/pacman.log)

**Comment by nikp123** [comment] 2023-07-13 13:54
you upgraded scrcpy 2.0 -> 2.1, that may be our clue

**Comment by nikp123** [comment] 2023-07-13 14:01
Yep confirmed on scrcpy 2.1, we have the EXACT same issue.

**Comment by kinostl** [comment] 2023-07-13 14:18
Activating a second instance does not fix it for me. 
![image](https://github.com/nikp123/scrcpy-desktop/assets/1018578/6b5e2824-0ae3-43ef-b290-b1088ab448ee)

**Comment by nikp123** [comment] 2023-07-13 14:18
This is an upstream regression, since Android is reporting the correct "virtual resolution" via ``dumpsys display``. Might have to file this over at scrcpy.

**Comment by nikp123** [comment] 2023-07-13 14:22
There isn't much I can do apart from getting this fixed in upstream?

**Comment by nikp123** [comment] 2023-07-13 14:32
Weird, I guess its a per machine behaviour.

**Comment by nikp123** [comment] 2023-07-13 14:43
> Already filed at [Genymobile/scrcpy#4157](https://github.com/Genymobile/scrcpy/issues/4157) Seems that their crop thing is not up to snuff. I'll try making it work with the `--crop` parameter.

``--crop`` doesn't really help, it's still the wrong display output. We'll have to wait for an update from upstream.

**Comment by nikp123** [comment] 2023-07-14 10:03
Seems to be fixed in a future release, we just need to wait for it to get released.

**Comment by UnsavedTrash** [comment] 2023-07-14 12:43
I can also confirm that the downgrade to scrcpy 2.0.1 fixed the issue for me.

**Comment by nikp123** [comment] 2023-07-21 13:21
Scrcpy 2.1.1 fixes this. Closing.

**Closed by nikp123** 2023-07-21 13:21 UTC
